#!/bin/bash

gcc -Wall -pg test_gprof.c test_gprof_new.c -o test_gprof

./test_gprof

gprof test_gprof gmon.out > analysis.txt

gprof -a test_gprof gmon.out > analysis.txt

sudo perf record ./test_gprof

sudo perf report

